services:
  - type: web
    name: sanjay-portfolio
    env: node
    plan: free
    buildCommand: npm install--legacy-peer-deps && npm install mongodb --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
    healthCheckPath: /
